name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure to use Node.js v18+

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli

      - name: Install frontend dependencies
        run: |
          cd zoyAdminAngular
          npm install

      - name: Build frontend
        run: |
          cd zoyAdminAngular
          ng build --configuration production --base-href /admin/

      - name: Upload frontend build as artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: zoyAdminAngular/dist/zoyadminportal/*

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download frontend build artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: ./frontend-build

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Frontend to Server
        run: |
          echo "Copying frontend to server..."
          scp -r ./frontend-build/* ubuntu@45.129.86.68:/var/www/html/admin/
