jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Build frontend
        run: |
          npm run build
        # Ensure this command generates the 'frontend-build' directory

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./frontend-build/

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Download frontend build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build

      - name: Copy Frontend to Server
        run: |
          echo "Copying frontend to server..."
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./frontend-build/* ubuntu@45.129.86.68:/var/www/html/admin/
