name: CI/CD Pipeline
#work
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Step 4: Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd zoyAdminAngular
          npm install

      # Step 5: Build the Angular frontend for production
      - name: Build frontend
        run: |
          cd zoyAdminAngular
          ng build --configuration production --base-href /admin/

      # Step 6: Upload the build artifacts (using v4)
      - name: Upload frontend build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: zoyAdminAngular/dist/zoyadminportal/

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend

    steps:
      # Step 1: Download the build artifacts from the previous job
      - name: Download frontend build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./frontend-build

      # Step 2: Set up SSH keys for secure deployment
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Debug frontend-build contents
      - name: Debug frontend-build contents
        run: ls -R ./frontend-build/

      # Step 4: Copy the build files to the server
      - name: Copy Frontend to Server
        run: |
          echo "Copying frontend to server..."
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./frontend-build/* ubuntu@45.129.86.68:/tmp/frontend/
          ssh ubuntu@45.129.86.68 "sudo mkdir -p /var/www/html/admin && sudo mv /tmp/frontend/* /var/www/html/admin/"

      # Step 5: Debug server directory contents
      - name: Debug server directory contents
        run: ssh ubuntu@45.129.86.68 "ls -l /var/www/html/admin/"