name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch as needed
  pull_request:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Set the version to 18.x

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli

      - name: Install frontend dependencies
        run: |
          cd zoyAdminAngular
          npm install

      - name: Build frontend
        run: |
          cd zoyAdminAngular
          ng build --configuration production --base-href /admin/

      - name: List build directory contents with full path
        run: |
          echo "Listing build directory contents..."
          ls -al /home/runner/work/zoyadmin/zoyadmin/zoyAdminAngular/dist/zoyadminportal

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Frontend to Server
        run: |
          echo "Copying frontend to server..."
          scp -r /home/runner/work/zoyadmin/zoyadmin/zoyAdminAngular/dist/zoyadminportal/* ubuntu@45.129.86.68:/var/www/html/admin/
