name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch as needed
  pull_request:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Set the version to 18.x

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli

      - name: Install frontend dependencies
        run: |
          cd zoyAdminAngular
          npm install

      - name: Build frontend
        run: |
          cd zoyAdminAngular
          ng build --configuration production --base-href /admin/

  build_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Fix here
          architecture: 'x64'
          check-latest: false

      - name: Build backend
        run: |
          cd zoyAdminServer
          mvn clean install -DskipTests=true -Pqa  # Your specified backend build command

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build_frontend
      - build_backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check Frontend build
        run: |
          ls -al zoyAdminAngular/dist/zoyadminportal

      - name: Check Backend build
        run: |
          ls -al zoyAdminServer/target

      - name: Copy Frontend to Server
        run: |
          echo "Copying frontend to server..."
          scp -r zoyAdminAngular/dist/zoyadminportal/* ubuntu@45.129.86.68:/var/www/html/admin/

      - name: Copy Backend to Server
        run: |
          echo "Copying backend to server..."
          scp zoyAdminServer/target/zoy-admin-server.jar ubuntu@45.129.86.68:/path/to/your/backend/

      - name: Run Docker container on server
        run: |
          echo "Running Docker container on server..."
          ssh ubuntu@45.129.86.68 << EOF
            docker pull your_docker_image_name
            docker run -d -p 8080:8080 your_docker_image_name
          EOF
